services:
  - type: web
    name: portfolio
    env: python
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn portfolio.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: "3.13.0"
